### ISSUE TITLE
File Upload doesn't work

### ISSUE THREAD

**Issue by ThamanVelasquezBice** [austinkregel/Warden#6]
I have a model that has 'file_path' as a fillable attribute, but when I submit the form the image path is saved as `/tmp/phpfyujWO`. I looked over my system and can not find that file path anywhere. Any help?

P.S. I am using version 5.2

Cheers,
Thaman

**Comment by austinkregel** [comment]
So, I'll be addressing this soon. Probably this week or next. It's something I've been debating how and where everything should be stored and how everything should be retrieved...

**Comment by austinkregel** [comment]
Completed file uploads in [latest commit](https://github.com/austinkregel/Warden/commit/6f5a98bd79a488f0f300f4851061ac6f7d19f8a3)
